services:
  frontend:
    build: ./frontend
    ports:
      - "8090:80"
    depends_on:
      - backend-api
    networks:
      - webnet

  backend-api:
    build: ./backend-api
    ports:
      - "8010:8000"
    environment:
      - AI_ENGINE_URL=http://ai-engine:5005
    networks:
      - webnet

  ai-engine:
    build: ./ai-engine
    ports:
      - "5005:5005"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
