version: "3.8"
services:
  ai-engine:
    build: ./ai-engine
    ports:
      - "5005:5005"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    restart: always

  backend-api:
    build: ./backend-api
    ports:
      - "8010:8010"
    environment:
      - AI_ENGINE_URL=http://ai-engine:5005
    depends_on:
      - ai-engine
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8090:80"
    environment:
      - VITE_API_URL=http://51.75.240.22:8010
    restart: always
